Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -64,7 +64,11 @@ jobs:
       
       - name: Decode Keystore
         run: |
-          echo "${{ secrets.KEYSTORE_BASE64 }}" | tr -d '\r\n' | grep -v "CERTIFICATE" | base64 --decode > android/app/motogps-release.jks
+          echo "${{ secrets.KEYSTORE_BASE64 }}" | tr -d '\r\n' | base64 --decode > android/app/motogps-release.jks
+          if [ ! -s android/app/motogps-release.jks ]; then
+            echo "ERROR: El keystore está vacío o no se decodificó correctamente"
+            exit 1
+          fi
 
       - name: Build AAB Release
         run: flutter build appbundle --release --dart-define=MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}
